version: '3.1'

services:
  php:
    build: ./php
    ports:
      - 8089:80
 
  db:
    image: mariadb:10.6
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1